#!/bin/bash

set -e

PROJECT_NAME="haskell-playground"

echo "$(date): reloading the REPL..."

# This assumes the REPL is started in the first pane
tmux send-keys -t "$PROJECT_NAME:0" ":!clear" Enter
tmux send-keys -t "$PROJECT_NAME:0" ":reload" Enter
tmux send-keys -t "$PROJECT_NAME:0" ':main --format=progress --match ""' Enter
